name = "naverv-daily-collector"
main = "index.ts"
compatibility_date = "2026-05-27"

[triggers]
crons = ["30 2 * * *"]

[[d1_databases]]
binding = "DB"
database_name = "naverv-db"
database_id = "c3a124bf-f795-4d6a-b8b9-a03db460591d"
